// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26.2.2026, 16:29:15
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/Study/js-fe-2025Q3/SkillGrove/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/plugins/**/*.{js,ts,mjs}","E:/Study/js-fe-2025Q3/SkillGrove/app/composables/**/*.{js,ts,mjs}","E:/Study/js-fe-2025Q3/SkillGrove/app/utils/**/*.{js,ts,mjs}","E:/Study/js-fe-2025Q3/SkillGrove/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Study/js-fe-2025Q3/SkillGrove/app/app.config.{js,ts,mjs}"]}},
{"theme":{"extend":{"colors":{"primary":{"50":"#f0fdf4","100":"#dcfce7","200":"#bbf7d0","300":"#86efac","400":"#4ade80","500":"#22c55e","600":"#16a34a","700":"#15803d","800":"#166534","900":"#14532d","950":"#052e16"}}}}},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;